apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: steamvr
  name: steamvr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: steamvr
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: steamvr
    spec:
      containers:
        - securityContext:
            capabilities:
              add:
                - ALL
                - NET_ADMIN
                - NET_RAW
                - SYS_ADMIN
            privileged: true
          env:
          image: ghcr.io/celesrenata/steamvr:latest
          imagePullPolicy: Always
          name: steamvr
          ports:
            - containerPort: 3350
              protocol: TCP
            - containerPort: 22
              protocol: TCP
            - containerPort: 3389 
              protocol: TCP
            - containerPort: 27036
              protocol: TCP
            - containerPort: 27037
              protocol: TCP
            - containerPort: 10400
              protocol: UDP
            - containerPort: 10401
              protocol: UDP
            - containerPort: 9943
              protocol: TCP
            - containerPort: 9943
              protocol: UDP
            - containerPort: 9944
              protocol: TCP
            - containerPort: 9944
              protocol: UDP
          resources:
            requests:
              cpu: 0.1
              memory: 2Gi
            limits:
               cpu: 12
               memory: 64Gi
               nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: /workspace
              name: steamvr-workspace
            - mountPath: /home/workspace
              name: steamvr-home
            - mountPath: /dev/shm
              name: dshm
           # - mountPath: /var/run/dbus
           #   name: dbus
            - mountPath: /dev/input
              name: dev 
            - mountPath: /mnt/games
              name: steamvr-games
      restartPolicy: Always
      volumes:
        - name: steamvr-workspace
          persistentVolumeClaim:
            claimName: steamvr-workspace
        - name: steamvr-home
          persistentVolumeClaim:
            claimName: steamvr-home
        - name: dshm
          emptyDir:
            medium: Memory
       # - name: dbus
       #   hostPath:
       #     path: "/var/run/dbus"
        - name: dev 
          hostPath:
            path: "/dev/input"
        - name: steamvr-games
          persistentVolumeClaim:
            claimName: steamvr-games
