apiVersion: v1
kind: PersistentVolume
metadata:
  name: steamvr-home
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  storageClassName: ""
  nfs:
    path: /volume1/Kubernetes/steamvr/home     # The path to your config 
    server: 192.168.42.8     # Your NFS server with Media
  mountOptions:
    - vers=4
    - minorversion=1
    - noac
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: steamvr-games
spec:
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local
  local:
    path: /var/lib/SteamVR/games     # The path to your config
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gremlin-1
