apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: steamvr-workspace
  name: steamvr-workspace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: steamvr-home
  name: steamvr-home
spec:
  volumeName: steamvr-home
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: steamvr-games
  name: steamvr-games
spec:
  volumeName: steamvr-games
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
