apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: steamvr-snapshot
  namespace: longhorn-system 
spec:
  cron: "0 */2 * * *"
  task: "snapshot"
  groups:
  - steamvr-service
  retain: 40
  concurrency: 2
  labels:
    label/1: a
    label/2: b
